### ISSUE TITLE
Title Search gives "unable to open database file" error

### ISSUE THREAD

**Issue by woojoo666** [nixgates/Incursion#87]
Just installed Incursion repo and Anime Incursion (v1.1), and after opening Anime Incursion, when I tried to click "Title Search" I got the error:

	03:48:07.786 T:510355743984   ERROR: GetDirectory - Error getting
	03:48:10.885 T:510762104048   ERROR: Previous line repeats 6 times.
	03:48:10.885 T:510762104048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
	                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
	                                            Error Type: <class 'sqlite3.OperationalError'>
	                                            Error Contents: unable to open database file
	                                            Traceback (most recent call last):
	                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.animeincursion/animeincursion.py", line 80, in <module>
	                                                navigator().search()
	                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.animeincursion/lib/navigator.py", line 181, in search
	                                                dbcon = database.connect(control.searchFile)
	                                            OperationalError: unable to open database file
	                                            -->End of Python script error report<--
	03:48:11.015 T:510819050736   ERROR: GetDirectory - Error getting plugin://plugin.video.animeincursion/?action=search
	03:48:11.016 T:510819050736   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.animeincursion/?action=search) failed

**Comment by woojoo666** [comment]
ok so I "fixed" it. After clicking the "TV Shows" section, when I went back and clicked "Title Search" it worked. So I'm guessing the database file isn't being created until I click "TV Shows".
